name: Canary Release
on:
  pull_request:
    types: [ opened, synchronize, labeled ]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Imitate Canary Release
        uses: actions/github-script@v6
        with:
          script: |
            console.log(context);