name: Test
on: push

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
          uses: actions/checkout@v2
          with:
            fetch-depth: 0
      - name: "Setup npm"
        run: |
          npm install
      - name: "Run tests"
        run: npx lerna run test
